services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    env_file:
      - src/config/.env.vault.secrets
#    environment:
#      - VAULT_DEV_ROOT_TOKEN_ID=my_super_secret_root_token
#      - VAULT_ADDR=http://0.0.0.0:8200
#      - VAULT_API_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - ./config:/vault/config
      - ./scripts:/vault/scripts
    command: server -dev
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 3

  vault-init:
    build:
      context: .
      dockerfile: Dockerfile.init
    container_name: vault-init
    depends_on:
      vault:
        condition: service_healthy
    env_file:
      - src/config/.env.vault-init.secrets
#    environment:
#      - VAULT_ADDR=http://vault:8200
#      - VAULT_TOKEN=my_super_secret_root_token
    volumes:
      - ./scripts:/scripts:ro
      - ./config:/config:ro
    entrypoint: ["sh"]
    command: ["/scripts/init-vault.sh"]

